# read an image

In [2]:
import cv2
img=cv2.imread('lena.jpg',1)
cv2.imshow('image',img)
print(img)
k=cv2.waitKey(0)
if k==27:
    cv2.destroyAllWindows()
elif k==ord('n'):
    cv2.imwrite('lena_copy.png',img)
    cv2.destroyAllWindows()

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


# how to capture live video

In [ ]:
import cv2
cap=cv2.VideoCapture(0);
fourcc=cv2.VideoWriter_fourcc(*'XVID')
out=cv2.VideoWriter('output.avi',fourcc,20.0, (640,480))



print(cap.isOpened())
while(cap.isOpened()):
    ret,frame=cap.read()
    if ret==True:
        print(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    
        print(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    
        gray=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    
        cv2.imshow('video',gray)
        if cv2.waitKey(1)==ord('q'):
            break
    else:
        break
    
cap.release()
out.release()

cv2.destroyAllWindows()


# insert line,circle,rectangle on the image

In [ ]:
import numpy as np
import cv2
img=cv2.imread('lena.jpg',1)

img=cv2.line(img,(0,0),(512,512),(0,0,255),2)
img=cv2.arrowedLine(img,(0,512),(255,0),(0,255,0),10)
cv2.imshow('image',img)


cv2.waitKey(0)

cv2.destroyAllWindows()

In [ ]:
import numpy as np
import cv2
img=cv2.imread('lena.jpg',1)

img=cv2.line(img,(0,0),(512,512),(0,0,255),2)
img=cv2.arrowedLine(img,(0,512),(500,0),(0,255,0),10)

img=cv2.rectangle(img,(194,52),(313,154),(0,255,0),5,-1)
cv2.imshow('image',img)


k = cv2.waitKey(0)
if k==27:
    cv2.destroyAllWindows()

In [ ]:
import numpy as np
import cv2
img=cv2.imread('lena.jpg',1)

img=cv2.line(img,(0,0),(512,512),(0,0,255),2)
img=cv2.arrowedLine(img,(0,512),(500,0),(0,255,0),10)

img=cv2.rectangle(img,(194,52),(313,154),(0,0,255),-1)

img=cv2.circle(img,(240,440),65,(0,255,0),-1)

cv2.imshow('image',img)


k = cv2.waitKey(0)
if k==27:
    cv2.destroyAllWindows()

In [ ]:
import numpy as np
import cv2
img=cv2.imread('lena.jpg',1)

font=cv2.FONT_ITALIC

cv2.putText(img,'Learning OpenCV',(150,200),font,2,(255,255,255),5,cv2.LINE_AA)

cv2.imshow('image',img)


k = cv2.waitKey(0)
if k==27:
    cv2.destroyAllWindows()

# how to put text on the image

In [ ]:
import numpy as np
import cv2
#img=cv2.imread('lena.jpg',1)
img=np.zeros([512,512,3],np.uint8)

font=cv2.FONT_ITALIC

img=cv2.rectangle(img,(194,52),(313,154),(0,0,255),-1)

img=cv2.circle(img,(240,440),65,(0,255,0),-1)

cv2.putText(img,'Learning OpenCV',(10,200),font,2,(0,255,255),3,cv2.LINE_AA)

cv2.imshow('image',img)


k = cv2.waitKey(0)
if k==27:
    cv2.destroyAllWindows()

In [ ]:
import cv2
cap=cv2.VideoCapture(0)

print(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    
print(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

cap.set(3,1208)
cap.set(4,720)

print(cap.get(3))
print(cap.get(4))

print(cap.isOpened())
while(cap.isOpened()):
    ret,frame=cap.read()
    if ret==True:
            
        gray=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    
        cv2.imshow('video',gray)
        if cv2.waitKey(1)==ord('q'):
            break
    else:
        break
    
cap.release()

cv2.destroyAllWindows()


In [ ]:
import cv2
cap=cv2.VideoCapture(0)

print(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    
print(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

cap.set(3,1208)
cap.set(4,720)

print(cap.get(3))
print(cap.get(4))

print(cap.isOpened())
while(cap.isOpened()):
    ret,frame=cap.read()
    if ret==True:
            
        gray=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    
        cv2.imshow('video',gray)
        if cv2.waitKey(1)==ord('q'):
            break
    else:
        break
    
cap.release()

cv2.destroyAllWindows()

In [ ]:
import cv2
import datetime

cap=cv2.VideoCapture(0)

print(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    
print(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

#cap.set(3,640)
#cap.set(4,480)

#print(cap.get(3))
#print(cap.get(4))

print(cap.isOpened())
while(cap.isOpened()):
    ret,frame=cap.read()
    if ret==True:
            
        font=cv2.FONT_HERSHEY_SIMPLEX 
        
        text='Width:'+str(cap.get(3))+ ' Height:'+str(cap.get(4))
       
        datet=str(datetime.datetime.now())
        
        frame=cv2.putText(frame,datet,(10,30),font,1,(0,255,255),1,cv2.LINE_AA)
        
        cv2.imshow('video',frame)
        if cv2.waitKey(1)==ord('q'):
            break
    else:
        break
    
cap.release()

cv2.destroyAllWindows()

In [ ]:
import numpy as np
import cv2
events=[ i for i in dir(cv2) if 'EVENT' in i]
print(events)

In [ ]:
import cv2
import numpy as np
def click_event(event,x,y,flags,param):

    if event==cv2.EVENT_LBUTTONDOWN:
        print(x,',  ',y)
       
        font=cv2.FONT_HERSHEY_SIMPLEX
        
              
        strXY=str(x) +',  '+ str(y)
            
        cv2.putText(img,strXY,(x,y),font,1,(255,255,0),2)
            
        cv2.imshow('image',img)
            
img=np.zeros([512,512,3],np.uint8)

cv2.imshow('image',img)

cv2.setMouseCallback('image',click_event)

k=cv2.waitKey(0)
if k==27:
    cv2.destroyAllWindows()

In [ ]:
import numpy as np
import cv2

def click_event(event,x,y,flags,param):

    if event==cv2.EVENT_LBUTTONDOWN:
        print(x,',  ',y)
       
        font=cv2.FONT_HERSHEY_SIMPLEX
        
              
        strXY=str(x) +',  '+ str(y)
            
        cv2.putText(img,strXY,(x,y),font,0.5,(255,255,0),2)
                        
        cv2.imshow('image',img)
        
    if event==cv2.EVENT_RBUTTONDOWN:
        
        blue=img[y,x,0]
        green=img[y,x,1]
        red=img[y,x,2]
        
               
        font=cv2.FONT_HERSHEY_SIMPLEX
        
        strBGR=str(blue) +',  '+ str(green) +',  '+str(red)
            
        cv2.putText(img,strBGR,(x,y),font,0.5,(0,255,255),2)
                        
        cv2.imshow('image',img)
        
        
            
img=np.zeros([512,512,3],np.uint8)

cv2.imshow('image',img)

cv2.setMouseCallback('image',click_event)

k=cv2.waitKey(0)
if k==27:
    cv2.destroyAllWindows()

In [ ]:
import cv2

def click_event(event,x,y,flags,param):

    if event==cv2.EVENT_LBUTTONDOWN:
        print(x,',  ',y)
       
        font=cv2.FONT_HERSHEY_SIMPLEX
        
              
        strXY=str(x) +',  '+ str(y)
            
        cv2.putText(img,strXY,(x,y),font,0.5,(255,255,0),2)
                        
        cv2.imshow('image',img)
        
    if event==cv2.EVENT_RBUTTONDOWN:
        
        blue=img[y,x,0]
        green=img[y,x,1]
        red=img[y,x,2]
        
               
        font=cv2.FONT_HERSHEY_SIMPLEX
        
        strBGR=str(blue) +',  '+ str(green) +',  '+str(red)
            
        cv2.putText(img,strBGR,(x,y),font,0.5,(0,255,255),2)
                        
        cv2.imshow('image',img)
        
        
            
img=cv2.imread('lena.jpg',1)

cv2.imshow('image',img)

cv2.setMouseCallback('image',click_event)

k=cv2.waitKey(0)
if k==27:
    cv2.destroyAllWindows()

In [ ]:
import cv2

def click_event(event,x,y,flags,param):

    if event==cv2.EVENT_LBUTTONDOWN:
        print(x,',  ',y)
       
        font=cv2.FONT_HERSHEY_SIMPLEX
        
              
        strXY=str(x) +',  '+ str(y)
            
        cv2.putText(img,strXY,(x,y),font,0.5,(255,255,0),2)
                        
        cv2.imshow('image',img)
        
    if event==cv2.EVENT_RBUTTONDOWN:
        
        blue=img[y,x,0]
        green=img[y,x,1]
        red=img[y,x,2]
        
               
        font=cv2.FONT_HERSHEY_SIMPLEX
        
        strBGR=str(blue) +',  '+ str(green) +',  '+str(red)
            
        cv2.putText(img,strBGR,(x,y),font,0.5,(0,255,255),2)
                        
        cv2.imshow('image',img)
        
        
            
img=cv2.imread('lena.jpg',1)

cv2.imshow('image',img)

cv2.setMouseCallback('image',click_event)

k=cv2.waitKey(0)
if k==27:
    cv2.destroyAllWindows()

In [ ]:
import cv2
import numpy as np

def click_event(event,x,y,flags,param):

    if event==cv2.EVENT_LBUTTONDOWN:
        
        cv2.circle(img,(x,y),3,(0,0,255),-1,)
        
        points.append((x,y))
        if len(points)>=2:
            cv2.line(img,points[-1],points[-2],(255,0,0),5 )
        
        cv2.imshow('image',img)
   
        
        
img=np.zeros((512,512,3),np.uint8)           

#img=cv2.imread('lena.jpg',1)

cv2.imshow('image',img)

points=[]

cv2.setMouseCallback('image',click_event)

k=cv2.waitKey(0)
if k==27:
    cv2.destroyAllWindows()

In [ ]:
import cv2
import numpy as np

def click_event(event,x,y,flags,param):

    if event==cv2.EVENT_LBUTTONDOWN:
        
        blue=img[x,y,0]
        green=img[x,y,1]
        red=img[x,y,2]
        cv2.circle(img,(x,y),3,(0,0,255),-1)
        mycolorimage=np.zeros((512,512,3),np.uint8)
        
        mycolorimage[:]=[blue,green,red]
        
        cv2.imshow('color',mycolorimage)
   
        
        
#img=np.zeros((512,512,3),np.uint8)           

img=cv2.imread('lena.jpg',1)

cv2.imshow('image',img)

points=[]

cv2.setMouseCallback('image',click_event)

k=cv2.waitKey(0)
if k==27:
    cv2.destroyAllWindows()

In [ ]:
import cv2
import numpy as np
img=cv2.imread('messi5.jpg')
print(img.shape)
print(img.size)
print(img.dtype)

b,g,r=cv2.split(img)
img=cv2.merge((b,g,r))

ball=img[280:340, 330:390]

img[273:333, 100:160]=ball

cv2.imshow('image',img)

k=cv2.waitKey(0)
if k==27:
    cv2.destroyAllWindows()

In [ ]:
import cv2
import numpy as np
img=cv2.imread('messi5.jpg')

img2=cv2.imread('opencv-logo.png') 

print(img.shape)
print(img.size)
print(img.dtype)

b,g,r=cv2.split(img)
img=cv2.merge((b,g,r))

ball=img[280:340, 330:390]

img[273:333, 100:160]=ball

img=cv2.resize(img,(512,512))

img2=cv2.resize(img2,(512,512))

#dst=cv2.add(img,img2)

dst=cv2.addWeighted(img,.9,img2,.2,0);

cv2.imshow('image',dst)

k=cv2.waitKey(0)
if k==27:
    cv2.destroyAllWindows()

In [ ]:
import cv2
import numpy as np

img1=np.zeros((512,512,3),np.uint8)
img1=cv2.rectangle(img1,(200,0),(300,100),(255,255,255),-1)

img2=cv2.imread('lena.jpg')

#img2=cv2.resize(img2,(250,500))

#bitAnd=cv2.bitwise_and(img1,img2)

#bitxor=cv2.bitwise_xor(img1,img2)

bitnot1=cv2.bitwise_not(img1)
bitnot2=cv2.bitwise_not(img2)

cv2.imshow('image1',img1)
cv2.imshow('image2',img2)
cv2.imshow('bitnot1',bitnot1)
cv2.imshow('bitnot2',bitnot2)

k=cv2.waitKey(0)
if k==27:
    cv2.destroyAllWindows()

In [ ]:
import cv2
import numpy as np

def nothing(x):
    print(x)

img=np.zeros((300,512,3),np.uint8)
cv2.namedWindow('image')

cv2.createTrackbar('B','image',0,255,nothing)

cv2.createTrackbar('G','image',0,255,nothing)

cv2.createTrackbar('R','image',0,255,nothing)

k=cv2.waitKey(0)
if k==27:
    cv2.destroyAllWindows()               

In [ ]:
import cv2
import numpy as np

def nothing(x):
    print(x)

img=np.zeros((300,512,3),np.uint8)
cv2.namedWindow('image')

cv2.createTrackbar('B','image',0,255,nothing)

cv2.createTrackbar('G','image',0,255,nothing)

cv2.createTrackbar('R','image',0,255,nothing)

while(1):
    cv2.imshow('image',img)
    
    k=cv2.waitKey(1)
    if k==27:
        break
        
        
    b=cv2.getTrackbarPos('B','image')
    g=cv2.getTrackbarPos('G','image')
    r=cv2.getTrackbarPos('R','image')
    
    
    img[:]=[b,g,r]
    
cv2.destroyAllWindows()
                
                
                
                

In [ ]:
import cv2
import numpy as np

def nothing(x):
    print(x)

img=np.zeros((300,512,3),np.uint8)
cv2.namedWindow('image')

cv2.createTrackbar('B','image',0,255,nothing)

cv2.createTrackbar('G','image',0,255,nothing)

cv2.createTrackbar('R','image',0,255,nothing)

switch='0:OFF\n 1:ON'

cv2.createTrackbar(switch,'image',0,1,nothing)

while(1):
    cv2.imshow('image',img)
    
    k=cv2.waitKey(1)
    if k==27:
        break
        
        
    b=cv2.getTrackbarPos('B','image')
    g=cv2.getTrackbarPos('G','image')
    r=cv2.getTrackbarPos('R','image')
    s=cv2.getTrackbarPos(switch,'image')
    
    if s==0:
        img[:]=0
    else:
        img[:]=[b,g,r]
    
cv2.destroyAllWindows()
                
                
                
                

In [ ]:
import cv2
import numpy as np

def nothing(x):
    print(x)

cv2.namedWindow('image')

cv2.createTrackbar('CP','image',10,400,nothing)



switch='color/gray'

cv2.createTrackbar(switch,'image',0,1,nothing)

while(1):
    img=cv2.imread('lena.jpg')
    pos=cv2.getTrackbarPos('CP','image')
    font=cv2.FONT_HERSHEY_SIMPLEX
    cv2.putText(img,str(pos),(50,150),font,4,(0,0,255),10,6)
    
    k=cv2.waitKey(1)
    if k==27:
        break
        
        
   
    s=cv2.getTrackbarPos(switch,'image')
   
    
    if s==0:
        pass
    else:
        img=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
        
    img=cv2.imshow('image',img)
    
cv2.destroyAllWindows()
                
                
                
                

In [ ]:
import cv2
import numpy as np

#cv2.namedWindow('Tracking')

img=cv2.imread('smarties.png')
hsv=cv2.cvtColor(img,cv2.COLOR_BGR2HSV)

l_b=np.array([110,50,50])
u_b=np.array([130,255,255])

mask=cv2.inRange(hsv,l_b,u_b)

res=cv2.bitwise_and(img,img,mask=mask)

cv2.imshow('image',img)
cv2.imshow('mask',mask)
cv2.imshow('res',res)
k=cv2.waitKey(0)
if k==27:
    cv2.destroyAllWindows()

In [ ]:
import cv2
import numpy as np

def nothing(x):
    pass

cv2.namedWindow('Tracking')
cv2.createTrackbar('LH','Tracking',0,255,nothing())
cv2.createTrackbar('LS','Tracking',0,255,nothing())
cv2.createTrackbar('LV','Tracking',0,255,nothing())
cv2.createTrackbar('UH','Tracking',255,255,nothing())
cv2.createTrackbar('US','Tracking',255,255,nothing())
cv2.createTrackbar('UV','Tracking',255,255,nothing())


img=cv2.imread('smarties.png')
hsv=cv2.cvtColor(img,cv2.COLOR_BGR2HSV)

l_h=cv2.getTrackbarPos('LH','Tracking')
l_s=cv2.getTrackbarPos('LS','Tracking')
l_v=cv2.getTrackbarPos('LV','Tracking')

u_h=cv2.getTrackbarPos('UH','Tracking')
u_s=cv2.getTrackbarPos('US','Tracking')
u_v=cv2.getTrackbarPos('UV','Tracking')

l_b=np.array([l_h,l_s,l_v])
u_b=np.array([u_h,u_s,u_v])

mask=cv2.inRange(hsv,l_b,u_b)

res=cv2.bitwise_and(img,img,mask=mask)

cv2.imshow('image',img)
cv2.imshow('mask',mask)
cv2.imshow('res',res)
k=cv2.waitKey(0)
if k==27:
    cv2.destroyAllWindows()

In [ ]:
import cv2
import numpy as np

def nothing(x):
    pass
cap=cv2.VideoCapture(0)

cv2.namedWindow('Tracking')
cv2.createTrackbar('LH','Tracking',0,255,nothing)
cv2.createTrackbar('LS','Tracking',0,255,nothing)
cv2.createTrackbar('LV','Tracking',0,255,nothing)
cv2.createTrackbar('UH','Tracking',255,255,nothing)
cv2.createTrackbar('US','Tracking',255,255,nothing)
cv2.createTrackbar('UV','Tracking',255,255,nothing)

while True:
    #img=cv2.imread('smarties.png')
    
    _,video=cap.read()
    
    hsv=cv2.cvtColor(img,cv2.COLOR_BGR2HSV)

    l_h=cv2.getTrackbarPos('LH','Tracking')
    l_s=cv2.getTrackbarPos('LS','Tracking')
    l_v=cv2.getTrackbarPos('LV','Tracking')

    u_h=cv2.getTrackbarPos('UH','Tracking')
    u_s=cv2.getTrackbarPos('US','Tracking')
    u_v=cv2.getTrackbarPos('UV','Tracking')

    l_b=np.array([l_h,l_s,l_v])
    u_b=np.array([u_h,u_s,u_v])

    mask=cv2.inRange(hsv,l_b,u_b)

    res=cv2.bitwise_and(img,img,mask=mask)

    cv2.imshow('image',img)
    cv2.imshow('mask',mask)
    cv2.imshow('res',res)
    k=cv2.waitKey(1)
    if k==27:
        break

cap.release()        
cv2.destroyAllWindows()

# Hue,Saturation and Value operations on image

In [ ]:
import cv2
import numpy as np

def nothing(x):
    pass


#cap=cv2.VideoCapture(0);

cv2.namedWindow('Tracking')
cv2.createTrackbar('LH','Tracking',0,255,nothing)
cv2.createTrackbar('LS','Tracking',0,255,nothing)
cv2.createTrackbar('LV','Tracking',0,255,nothing)
cv2.createTrackbar('UH','Tracking',255,255,nothing)
cv2.createTrackbar('US','Tracking',255,255,nothing)
cv2.createTrackbar('UV','Tracking',255,255,nothing)

while True:
    img=cv2.imread('smarties.png')
    
    _, frame=cap.read()
    
    hsv=cv2.cvtColor(img,cv2.COLOR_BGR2HSV)

    l_h=cv2.getTrackbarPos('LH','Tracking')
    l_s=cv2.getTrackbarPos('LS','Tracking')
    l_v=cv2.getTrackbarPos('LV','Tracking')

    u_h=cv2.getTrackbarPos('UH','Tracking')
    u_s=cv2.getTrackbarPos('US','Tracking')
    u_v=cv2.getTrackbarPos('UV','Tracking')

    l_b=np.array([l_h,l_s,l_v])
    u_b=np.array([u_h,u_s,u_v])

    mask=cv2.inRange(hsv,l_b,u_b)

    res=cv2.bitwise_and(img,img,mask=mask)

    cv2.imshow('image',img)
    cv2.imshow('mask',mask)
    cv2.imshow('res',res)
    k=cv2.waitKey(1)
    if k==27:
        break

cap.release()        
cv2.destroyAllWindows()

# Hue,Saturation and Value operations on live video capture

In [ ]:
import cv2
import numpy as np

def nothing(x):
    pass


cap=cv2.VideoCapture(0);

cv2.namedWindow('Tracking')
cv2.createTrackbar('LH','Tracking',0,255,nothing)
cv2.createTrackbar('LS','Tracking',0,255,nothing)
cv2.createTrackbar('LV','Tracking',0,255,nothing)
cv2.createTrackbar('UH','Tracking',255,255,nothing)
cv2.createTrackbar('US','Tracking',255,255,nothing)
cv2.createTrackbar('UV','Tracking',255,255,nothing)

while True:
    #img=cv2.imread('smarties.png')
    
    _, frame=cap.read()
    
    hsv=cv2.cvtColor(frame,cv2.COLOR_BGR2HSV)

    l_h=cv2.getTrackbarPos('LH','Tracking')
    l_s=cv2.getTrackbarPos('LS','Tracking')
    l_v=cv2.getTrackbarPos('LV','Tracking')

    u_h=cv2.getTrackbarPos('UH','Tracking')
    u_s=cv2.getTrackbarPos('US','Tracking')
    u_v=cv2.getTrackbarPos('UV','Tracking')

    l_b=np.array([l_h,l_s,l_v])
    u_b=np.array([u_h,u_s,u_v])

    mask=cv2.inRange(hsv,l_b,u_b)

    res=cv2.bitwise_and(frame,frame,mask=mask)

    cv2.imshow('frame',frame)
    cv2.imshow('mask',mask)
    cv2.imshow('res',res)
    k=cv2.waitKey(1)
    if k==27:
        break

cap.release()    

cv2.destroyAllWindows()

In [ ]:
import numpy as np
import cv2

img=cv2.imread('gradient.png',0)

_,th1=cv2.threshold(img,110,255,cv2.THRESH_BINARY)

_,th2=cv2.threshold(img,110,255,cv2.THRESH_BINARY_INV)

_,th3=cv2.threshold(img,100,255,cv2.THRESH_TRUNC)

_,th4=cv2.threshold(img,110,255,cv2.THRESH_TOZERO)


cv2.imshow('image',img)

cv2.imshow('th1',th1)
cv2.imshow('th2',th2)
cv2.imshow('th3',th3)
cv2.imshow('th4',th4)

k=cv2.waitKey(0)
if k==27:
    cv2.destroyAllWindows()

# Detection of edge of an image using thresholding technqiues

In [ ]:
import numpy as np
import cv2

image=cv2.imread('aadhar card.jpg')

cv2.imshow('original image',image)

img=cv2.imread('aadhar card.jpg',0)

_,th1=cv2.threshold(img,110,255,cv2.THRESH_BINARY)

th2=cv2.adaptiveThreshold(img,255,cv2.ADAPTIVE_THRESH_MEAN_C, cv2.THRESH_BINARY, 25, 5);

th3=cv2.adaptiveThreshold(img,255,cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY, 25, 5);


cv2.imshow('image',img)

cv2.imshow('th1',th1)
cv2.imshow('th2',th2)
cv2.imshow('th3',th3)


k=cv2.waitKey(0)
if k==27:
    cv2.destroyAllWindows()

In [ ]:
import numpy as np
import cv2
from matplotlib import pyplot as plt
%matplotlib qt

img=cv2.imread('lena.jpg',1)

cv2.imshow('image',img)
img=cv2.cvtColor(img,cv2.COLOR_BGR2RGB)

plt.imshow(img)
#plt.xticks([])
#plt.yticks([])
plt.show()

cv2.waitKey(0)
cv2.destroyAllWindows()

# image thresholding using various techniques

In [ ]:
import numpy as np
import cv2
from matplotlib import pyplot as plt
%matplotlib qt

img=cv2.imread('65019.jpg',0)

_,th1=cv2.threshold(img,110,255,cv2.THRESH_BINARY)

_,th2=cv2.threshold(img,110,255,cv2.THRESH_BINARY_INV)

_,th3=cv2.threshold(img,100,255,cv2.THRESH_TRUNC)

_,th4=cv2.threshold(img,110,255,cv2.THRESH_TOZERO)

_,th5=cv2.threshold(img,110,255,cv2.THRESH_TOZERO_INV)

titles=['Original Image','Binary','Binary Inv','Trunc','Tozero','Tozero Inv']

images=[img,th1,th2,th3,th4,th5]

for i in range(6):
    plt.subplot(2,3,i+1)
    plt.imshow(images[i],'gray')
    plt.title(titles[i])
    plt.xticks([])
    plt.yticks([])

    

plt.show()




## Morphological transformation on binary image

In [ ]:
import numpy as np
import cv2
from matplotlib import pyplot as plt
%matplotlib qt

img=cv2.imread('smarties.png',0)

_,mask=cv2.threshold(img,220,255,cv2.THRESH_BINARY_INV)


kernal=np.ones((5,5),np.uint8)

dilation=cv2.dilate(mask,kernal,iterations=2)

erosion=cv2.erode(mask,kernal,iterations=1)

opening=cv2.morphologyEx(mask,cv2.MORPH_OPEN,kernal)

closing=cv2.morphologyEx(mask,cv2.MORPH_CLOSE,kernal)

mg=cv2.morphologyEx(mask,cv2.MORPH_GRADIENT,kernal)

th=cv2.morphologyEx(mask,cv2.MORPH_TOPHAT,kernal)




titles=['Original Image','mask','dilation','erosion','opening','closing','mg','th']

images=[img,mask,dilation,erosion,opening,closing,mg,th]

for i in range(8):
    
    plt.subplot(2,4,i+1)
    
    plt.imshow(images[i],'gray')
    
    plt.title(titles[i])
    
    plt.xticks([])
    plt.yticks([])

    

plt.show()


# dilation,erode,morphology ooperations on image

In [ ]:
import numpy as np
import cv2
from matplotlib import pyplot as plt
%matplotlib qt

img=cv2.imread('lena.jpg',0)

#_,mask=cv2.threshold(img,220,255,cv2.THRESH_BINARY_INV)


kernal=np.ones((5,5),np.uint8)

dilation=cv2.dilate(img,kernal,iterations=2)

erosion=cv2.erode(img,kernal,iterations=1)

opening=cv2.morphologyEx(img,cv2.MORPH_OPEN,kernal)

closing=cv2.morphologyEx(img,cv2.MORPH_CLOSE,kernal)

mg=cv2.morphologyEx(img,cv2.MORPH_GRADIENT,kernal)

th=cv2.morphologyEx(img,cv2.MORPH_TOPHAT,kernal)




titles=['Original Image','mask','dilation','erosion','opening','closing','mg','th']

images=[img,img,dilation,erosion,opening,closing,mg,th]

for i in range(8):
    
    plt.subplot(2,4,i+1)
    
    plt.imshow(images[i],'gray')
    
    plt.title(titles[i])
    
    plt.xticks([])
    plt.yticks([])

    

plt.show()


# image smoothing/blurring using different filters(linear filters)

In [ ]:
import numpy as np
import cv2
from matplotlib import pyplot as plt

img=cv2.imread('lena.jpg')

img=cv2.cvtColor(img,cv2.COLOR_BGR2RGB)

kernel=np.ones((5,5),np.float32)/25

dst=cv2.filter2D(img,-1,kernel)

blurr=cv2.blur(img,(5,5))

gblur=cv2.GaussianBlur(img,(5,5),0)

median=cv2.medianBlur(img,5)

bfilter=cv2.bilateralFilter(img,9,75,75)


titles=['Original Image','2D convolution','blurr','gblur','median','bfilter']

images=[img,dst,blurr,gblur,median,bfilter]

for i in range(6):
    
    plt.subplot(2,3,i+1)
    
    plt.imshow(images[i],'gray')
    
    plt.title(titles[i])
    
    plt.xticks([])
    plt.yticks([])

    

plt.show()

# edge detection using sobel,laplacian detectors

In [ ]:
import numpy as np
import cv2
from matplotlib import pyplot as plt

img=cv2.imread('messi5.jpg',cv2.IMREAD_GRAYSCALE)

#img=cv2.cvtColor(img,cv2.COLOR_BGR2RGB)

lap=cv2.Laplacian(img,cv2.CV_64F,ksize=3)

lap=np.uint8(np.absolute(lap))

sobelx=cv2.Sobel(img,cv2.CV_64F, 1,0)

sobely=cv2.Sobel(img,cv2.CV_64F, 0,1)

sobelx=np.uint8(np.absolute(sobelx))

sobely=np.uint8(np.absolute(sobely))

sobel=cv2.bitwise_or(sobelx,sobely)

edge=cv2.Canny(img,100,200)


titles=['Original Image','Laplacian','sobelx','sobely','sobel','edge']

images=[img,lap,sobelx,sobely,sobel,edge]

for i in range(6):
    
    plt.subplot(2,3,i+1)
    
    plt.imshow(images[i],'gray')
    
    plt.title(titles[i])
    
    plt.xticks([])
    plt.yticks([])

    

plt.show()


In [ ]:
import numpy as np
import cv2
from matplotlib import pyplot as plt
%matplotlib qt
img=cv2.imread('lena.jpg',0)

canny=cv2.Canny(img,100,200)



titles=['Original Image','canny']

images=[img,canny]

for i in range(2):
    
    plt.subplot(1,2,i+1)
    
    plt.imshow(images[i],'gray')
    
    plt.title(titles[i])
    
    plt.xticks([])
    plt.yticks([])

    

plt.show()


# canny edge detection of lena image with trackbars

In [ ]:
import cv2
import numpy as np
from matplotlib import pyplot as plt

def nothing(x):
    pass

cv2.namedWindow('image')

cv2.createTrackbar('th1','image',0,255,nothing)

cv2.createTrackbar('th2','image',255,255,nothing)


while True:
    
    img=cv2.imread('78019.jpg')
    
               
    th1=cv2.getTrackbarPos('th1','image')
    th2=cv2.getTrackbarPos('th2','image')
    edge=cv2.Canny(img,th1,th2)
        
    cv2.imshow('image',img)
    
    cv2.imshow('canny',edge)
   
    k=cv2.waitKey(1)
    if k==27:
        break
cv2.destroyAllWindows()
                
                
                
                

# canny edge detection of aadhar card using trackbars

In [ ]:
import cv2
import numpy as np


def nothing(x):
    pass


cv2.namedWindow('image')

cv2.createTrackbar('th1','image',0,255,nothing)

cv2.createTrackbar('th2','image',255,255,nothing)

while True:
    img=cv2.imread('65019.jpg')
    
    th1=cv2.getTrackbarPos('th1','image')
    
    th2=cv2.getTrackbarPos('th2','image')
    
    edge=cv2.Canny(img,th1,th2) 

    
    cv2.imshow('image',img)
    cv2.imshow('edge',edge)
    
    k=cv2.waitKey(1)
    if k==27:
        break

cv2.destroyAllWindows()

# lena image pyramid down

In [ ]:
import numpy as np
import cv2
from matplotlib import pyplot as plt

img=cv2.imread('lena.jpg')

layer=img.copy()

gp=[layer]

for i in range(6):
    layer=cv2.pyrDown(layer)
    
    gp.append(layer)
    
    cv2.imshow(str(i),layer)
    
    

cv2.imshow('original image',img)

cv2.waitKey(0)
cv2.destroyAllWindows()

# append two images

In [ ]:
import numpy as np
import cv2
from matplotlib import pyplot as plt

apple=cv2.imread('apple.jpg')

orange=cv2.imread('orange.jpg')

apple_orange=np.hstack((apple[:,:256],orange[:,256:]))

print(apple.shape)
print(orange.shape)



cv2.imshow('apple',apple)
cv2.imshow('orange',orange)
cv2.imshow('apple_orange',apple_orange)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
 import numpy as np
import cv2
from matplotlib import pyplot as plt

img=cv2.imread('opencv-logo.png')

imgray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

ret,thresh=cv2.threshold(imgray,127,255,0)

contours,heirarchy=cv2.findContours(thresh,cv2.RETR_TREE,cv2.CHAIN_APPROX_NONE)

print('Number of Contours=' + str(len(contours)))

print(contours[0])

cv2.drawContours(img,contours,-1,(0,255,255),3)

cv2.imshow('image',img)

cv2.imshow('imgage GRAY',imgray)

cv2.waitKey(0)
cv2.destroyAllWindows()


In [ ]:
import cv2
import numpy as np

cap=cv2.VideoCapture('vtest.avi')

ret,frame1=cap.read()

ret,frame2=cap.read()

while cap.isOpened():
    
    diff=cv2.absdiff(frame1,frame2)
    
    gray=cv2.cvtColor(diff,cv2.COLOR_BGR2GRAY)
    
    blur=cv2.GaussianBlur(gray,(5,5),0)
    
    _,thresh=cv2.threshold(blur,20,255,cv2.THRESH_BINARY)
    
    dilated=cv2.dilate(thresh,None,3)
    
    contours,_=cv2.findContours(dilated,cv2.RETR_TREE,cv2.CHAIN_APPROX_NONE)
    
    for contour in contours:
        (x,y,w,h)=cv2.boundingRect(contour)
        
        if cv2.contourArea(contour)<700:
            continue
        cv2.rectangle(frame1,(x,y),(x+w,y+h),(0,255,0),2)
        
        cv2.putText(frame1,'status:{}'.format('movement'),(10,20),cv2.FONT_HERSHEY_SIMPLEX,1,(0,0,255),3)
    #cv2.drawContours(frame1,contours,-1,(0,255,0),2)
    
    cv2.imshow('feed',frame1)
    
    frame1=frame2
    
    ret,frame2=cap.read()
    
    if cv2.waitKey(40)==27:
        
        break
        
        
cv2.destroyAllWindows()
cap.release()

In [ ]:
import numpy as np
import cv2
from matplotlib import pyplot as plt

img=cv2.imread('shapes.jpg')

imgrey=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

_,thresh=cv2.threshold(imgrey,240,255,cv2.THRESH_BINARY)

contours,_=cv2.findContours(thresh,cv2.RETR_TREE,cv2.CHAIN_APPROX_NONE)
    
for contour in contours:
    approx=cv2.approxPolyDP(contour,0.01*cv2.arcLength(contour,True),True)
    
    cv2.drawContours(img,[approx],0,(0,0,0),5)
    
    x=approx.ravel()[0]
    
    y=approx.ravel()[1]-8
    
    if len(approx)==3:
        cv2.putText(img,'triangle',(x,y),cv2.FONT_HERSHEY_COMPLEX,0.5,(0,0,0))
    elif len(approx)==4:
        x,y,w,h=cv2.boundingRect(approx)
        
        aspectRatio=float(w)/h
        
        print(aspectRatio)
        
        if aspectRatio>=0.95 and  aspectRatio<=1.05:
            
            cv2.putText(img,'square',(x,y),cv2.FONT_HERSHEY_COMPLEX,0.5,(0,0,0))
        else:
            cv2.putText(img,'rectangle',(x,y),cv2.FONT_HERSHEY_COMPLEX,0.5,(0,0,0))
            
    elif len(approx)==5:
        cv2.putText(img,'pentagon',(x,y),cv2.FONT_HERSHEY_COMPLEX,0.5,(0,0,0))
    elif len(approx)==10:
        cv2.putText(img,'star',(x,y),cv2.FONT_HERSHEY_COMPLEX,0.5,(0,0,0))
    else:
         cv2.putText(img,'circle',(x,y),cv2.FONT_HERSHEY_COMPLEX,0.5,(0,0,0))
    
        

cv2.imshow('image',img)
#cv2.imshow('imgrey',imgrey)


cv2.waitKey(0)
cv2.destroyAllWindows()

# Open cv Module Histogram on 18 nov.2019

In [ ]:
import numpy as np
from matplotlib import pyplot as plt
import cv2
%matplotlib qt

img=np.zeros((200,200),np.uint8)

cv2.rectangle(img,(0,100),(200,200),(255),-1)

cv2.rectangle(img,(0,50),(100,100),(127),-1)

cv2.imshow('image',img)
plt.hist(img.ravel(),256,[0,256])
plt.show()

cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
import numpy as np
from matplotlib import pyplot as plt
import cv2
%matplotlib qt

img=cv2.imread('lena.jpg')

hist=cv2.calcHist([img],[0],None,[256],[0,256])

plt.plot(hist)

#b, g, r=cv2.split(img)

#cv2.imshow('image',img)
#cv2.imshow('b',b)
#cv2.imshow('g',g)
#cv2.imshow('r',r)

#plt.hist(b.ravel(),256,[0,256])
#plt.hist(g.ravel(),256,[0,256])
#plt.hist(r.ravel(),256,[0,256])

plt.show()

cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
import numpy as np
from matplotlib import pyplot as plt
import cv2
%matplotlib qt

img=cv2.imread('messi5.jpg')

grey_img=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

template=cv2.imread('messi_face.png',0)

w,h=template.shape[::-1]

res=cv2.matchTemplate(grey_img,template,cv2.TM_CCOEFF_NORMED)

print(res)

threshold=0.95;

loc=np.where(res>=threshold)

print(loc)

for pt in zip(*loc[::-1]):
    cv2.rectangle(img,pt,(pt[0]+w,pt[1]+h),(0,255,0),2)

cv2.imshow('image',img)


cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
import cv2
import numpy as np
from matplotlib import pyplot as plt

img=cv2.imread('sudoku.png')
gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
edges=cv2.Canny(gray,50,150,apertureSize=3)

cv2.imshow('edges',edges)

lines=cv2.HoughLines(edges,1,np.pi/180,200)

for line in lines:
    rho,theta=line[0]
    a=np.cos(theta)
    b=np.sin(theta)
    
    x0=a*rho
    y0=b*rho
    
    x1=int(x0+1000*(-b))
    
    y1=int(y0+1000*(a))
    
    x2=int(x0-1000*(-b))
    
    y2=int(y0-1000*(a))
    
    cv2.line(img,(x1,y1),(x2,y2),(0,255,0),2)
    
cv2.imshow('image',img)

cv2.waitKey(0)
cv2.destroyAllWindows()
    


In [ ]:
import cv2
import numpy as np
from matplotlib import pyplot as plt

img=cv2.imread('road.jpg')
gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
edges=cv2.Canny(gray,150,250,apertureSize=3)

cv2.imshow('edges',edges)

lines=cv2.HoughLinesP(edges,1,np.pi/180,100,minLineLength=100,maxLineGap=10)

for line in lines:
    x1,y1,x2,y2= line[0]
    
    cv2.line(img,(x1,y1),(x2,y2),(0,255,0),2)
    
cv2.imshow('image',img)

cv2.waitKey(0)
cv2.destroyAllWindows()
    


# lane line detection

In [ ]:
import cv2
import numpy as np
from matplotlib import pyplot as plt

def region_of_interest(img,vertices):
    
    mask=np.zeros_like(img)
    #channel_count=img.shape[2]
    match_mask_color=255
    cv2.fillPoly(mask,vertices,match_mask_color)
    masked_image=cv2.bitwise_and(img,mask)
    return masked_image

def draw_the_lines(img,lines):
    img=np.copy(img)
    blank_image=np.zeros((img.shape[0],img.shape[1],3),dtype=np.uint8)
    
    for line in lines:
        for x1,y1,x2,y2 in line:
            cv2.line(blank_image,(x1,y1),(x2,y2),(0,255,0),3)
    img=cv2.addWeighted(img,0.8,blank_image,1,0.0)
    return img
        

image=cv2.imread('road.jpg')
image=cv2.cvtColor(img,cv2.COLOR_BGR2RGB)

print(image.shape)

height=image.shape[0]

width=image.shape[1]

region_of_interest_vertices=[
    (0,height),(width/2,height/2),(width,height)
]
gray_image=cv2.cvtColor(image,cv2.COLOR_RGB2GRAY)

canny_image=cv2.Canny(gray_image,100,200)

cropped_image=region_of_interest(canny_image,np.array([region_of_interest_vertices],np.int32))


lines=cv2.HoughLinesP(cropped_image,6,np.pi/60,160,None,minLineLength=40,maxLineGap=25)

image_with_line=draw_the_lines(image,lines)  
plt.imshow(image_with_line)
plt.show()


cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
import cv2
import numpy as np
from matplotlib import pyplot as plt

def region_of_interest(img,vertices):
    
    mask=np.zeros_like(img)
    #channel_count=img.shape[2]
    match_mask_color=255
    cv2.fillPoly(mask,vertices,match_mask_color)
    masked_image=cv2.bitwise_and(img,mask)
    return masked_image

def draw_the_lines(img,lines):
    img=np.copy(img)
    blank_image=np.zeros((img.shape[0],img.shape[1],3),dtype=np.uint8)
    
    for line in lines:
        for x1,y1,x2,y2 in line:
            cv2.line(blank_image,(x1,y1),(x2,y2),(0,0,255),2)
    img=cv2.addWeighted(img,0.8,blank_image,1,0.0)
    return img
        

image=cv2.imread('road.jpg')
image=cv2.cvtColor(img,cv2.COLOR_BGR2RGB)

print(image.shape)

height=image.shape[0]

width=image.shape[1]

region_of_interest_vertices=[
    (0,height),(width/2,height/2),(width,height)
]
gray_image=cv2.cvtColor(image,cv2.COLOR_RGB2GRAY)

canny_image=cv2.Canny(gray_image,100,200)

cropped_image=region_of_interest(canny_image,np.array([region_of_interest_vertices],np.int32))


lines=cv2.HoughLinesP(cropped_image,6,np.pi/60,160,None,minLineLength=40,maxLineGap=25)

image_with_lines=draw_the_lines(image,lines) 

plt.imshow(image_with_lines)
plt.show()


cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
import matplotlib.pylab as plt
import cv2
import numpy as np

def region_of_interest(img, vertices):
    mask = np.zeros_like(img)
    #channel_count = img.shape[2]
    match_mask_color = 255
    cv2.fillPoly(mask, vertices, match_mask_color)
    masked_image = cv2.bitwise_and(img, mask)
    return masked_image

def drow_the_lines(img, lines):
    img = np.copy(img)
    blank_image = np.zeros((img.shape[0], img.shape[1], 3), dtype=np.uint8)

    for line in lines:
        for x1, y1, x2, y2 in line:
            cv2.line(blank_image, (x1,y1), (x2,y2), (255, 0, 0), thickness=10)

    img = cv2.addWeighted(img, 0.8, blank_image, 1, 0.0)
    return img

image = cv2.imread('road.jpg')
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
print(image.shape)
height = image.shape[0]
width = image.shape[1]
region_of_interest_vertices = [
    (0, height),
    (width/2, height/2),
    (width, height)
]
gray_image = cv2.cvtColor(image, cv2.COLOR_RGB2GRAY)
canny_image = cv2.Canny(gray_image, 100, 200)
cropped_image = region_of_interest(canny_image,
                np.array([region_of_interest_vertices], np.int32),)
lines = cv2.HoughLinesP(cropped_image,
                        rho=6,
                        theta=np.pi/180,
                        threshold=160,
                        lines=np.array([]),
                        minLineLength=40,
                        maxLineGap=25)
image_with_lines = drow_the_lines(image, lines)
plt.imshow(image_with_lines)
plt.show()

In [ ]:
import matplotlib.pylab as plt
import cv2
import numpy as np

def region_of_interest(img, vertices):
    mask = np.zeros_like(img)
    #channel_count = img.shape[2]
    match_mask_color = 255
    cv2.fillPoly(mask, vertices, match_mask_color)
    masked_image = cv2.bitwise_and(img, mask)
    return masked_image

def drow_the_lines(img, lines):
    img = np.copy(img)
    blank_image = np.zeros((img.shape[0], img.shape[1], 3), dtype=np.uint8)

    for line in lines:
        for x1, y1, x2, y2 in line:
            cv2.line(blank_image, (x1,y1), (x2,y2), (255, 0, 0), thickness=10)

    img = cv2.addWeighted(img, 0.8, blank_image, 1, 0.0)
    return img

def process(image):
    print(image.shape)
    height = image.shape[0]
    width = image.shape[1]
    region_of_interest_vertices = [
        (0, height),
        (width/2, height/2),
        (width, height)
    ]
    gray_image = cv2.cvtColor(image, cv2.COLOR_RGB2GRAY)
    canny_image = cv2.Canny(gray_image, 100, 200)
    cropped_image = region_of_interest(canny_image,
                    np.array([region_of_interest_vertices], np.int32),)
    lines = cv2.HoughLinesP(cropped_image,
                            rho=6,
                            theta=np.pi/180,
                            threshold=160,
                            lines=np.array([]),
                            minLineLength=40,
                            maxLineGap=25)
    image_with_lines = drow_the_lines(image, lines)
    return image_with_lines


cap=cv2.VideoCapture('test_video.mp4')

while(cap.isOpened()):
    ret,frame=cap.read()
    frame=process(frame)
    cv2.imshow('frame',frame)
    if cv2.waitKey(1)==ord('q'):
        break
        
cap.release()
cv2.destroyAllWindows()

    


In [ ]:
import matplotlib.pylab as plt
import cv2
import numpy as np

def region_of_interest(img, vertices):
    mask = np.zeros_like(img)
    #channel_count = img.shape[2]
    match_mask_color = 255
    cv2.fillPoly(mask, vertices, match_mask_color)
    masked_image = cv2.bitwise_and(img, mask)
    return masked_image

def drow_the_lines(img, lines):
    img = np.copy(img)
    blank_image = np.zeros((img.shape[0], img.shape[1], 3), dtype=np.uint8)

    for line in lines:
        for x1, y1, x2, y2 in line:
            cv2.line(blank_image, (x1,y1), (x2,y2), (0, 255, 0), thickness=10)

    img = cv2.addWeighted(img, 0.8, blank_image, 1, 0.0)
    return img

# = cv2.imread('road.jpg')
#image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
def process(image):
    print(image.shape)
    height = image.shape[0]
    width = image.shape[1]
    region_of_interest_vertices = [
        (0, height),
        (width/2, height/2),
        (width, height)
    ]
    gray_image = cv2.cvtColor(image, cv2.COLOR_RGB2GRAY)
    canny_image = cv2.Canny(gray_image, 100, 120)
    cropped_image = region_of_interest(canny_image,
                    np.array([region_of_interest_vertices], np.int32),)
    lines = cv2.HoughLinesP(cropped_image,
                            rho=2,
                            theta=np.pi/180,
                            threshold=50,
                            lines=np.array([]),
                            minLineLength=40,
                            maxLineGap=100)
    image_with_lines = drow_the_lines(image, lines)
    return image_with_lines

cap = cv2.VideoCapture('test_video.mp4')

while cap.isOpened():
    ret, frame = cap.read()
    frame = process(frame)
    cv2.imshow('frame', frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()

In [ ]:
import numpy as np
import cv2
from matplotlib import pyplot as plt
img=cv2.imread('shapes.jpg')
output=img.copy()
gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
gray=cv2.medianBlur(gray,5)

circles=cv2.HoughCircles(gray,cv2.HOUGH_GRADIENT,1,20,param1=50,param2=30,minRadius=0,maxRadius=0)

detected_circles=np.uint16(np.around(circles))
for (x,y,r) in detected_circles[0,:]:
    cv2.circle(output,(x,y),r,(255,255,0),3)
    cv2.circle(output,(x,y),0,(0,255,255),3)


cv2.imshow('output',output)

cv2.waitKey(0)
cv2.destroyAllWindows()

# face detection in image

In [ ]:
import numpy as np
import cv2
from matplotlib import pyplot as plt

face_cascade=cv2.CascadeClassifier('haarcascade_frontalface_default.xml')

img=cv2.imread('naveen.jpg')
gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
faces=face_cascade.detectMultiScale(gray,1.1,4)

for (x,y,w,h) in faces:
    cv2.rectangle(img,(x,y),(x+w,y+h),(255,255,0),3)

cv2.imshow('image',img)

cv2.waitKey(0)
cv2.destroyAllWindows()

# face detection in video

In [ ]:
import cv2


face_cascade=cv2.CascadeClassifier('haarcascade_frontalface_default.xml')

cap=cv2.VideoCapture('test.mp4')

while cap.isOpened():
    _, img= cap.read()
    
    gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

    faces = face_cascade.detectMultiScale(gray,1.1,4)

    for (x, y, w, h) in faces:
        cv2.rectangle(img,(x,y),(x+w,y+h),(255,255,0),3)

    cv2.imshow('img',img)

    if cv2.waitKey(1)==ord('q'):
        break
    
cap.release()   
cv2.destroyAllWindows()

In [ ]:
import cv2

face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')

eye_cascade = cv2.CascadeClassifier('haarcascade_eye_tree_eyeglasses.xml')


cap = cv2.VideoCapture('test.mp4')

while cap.isOpened():
    _, img = cap.read()

    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(gray, 1.1, 4)

    for (x, y , w ,h) in faces:
        cv2.rectangle(img, (x,y), (x+w, y+h), (255, 0 , 0), 3)
        roi_gray=gray[y:y+h,x:x+w]
        roi_color=img[y:y+h,x:x+w]
        eyes = eye_cascade.detectMultiScale(roi_gray)
        for (ex,ey,ew,eh) in eyes:
            cv2.rectangle(roi_color,(ex,ey),(ex+ew,ey+eh),(0,255,0),5)

    # Display the output
    cv2.imshow('img', img)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()

In [ ]:
import numpy as np
import cv2

img = cv2.imread('chessboard.png')

cv2.imshow('img', img)
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

gray = np.float32(gray)
dst = cv2.cornerHarris(gray, 30, 3, 0.04)

dst = cv2.dilate(dst, None)

img[dst > 0.01 * dst.max()] = [0, 0, 255]

cv2.imshow('dst', img)

if cv2.waitKey(0) & 0xff == 27:
    cv2.destroyAllWindows()

In [ ]:
import numpy as np
import cv2 as cv

img = cv.imread('pic1.png')

gray = cv.cvtColor(img, cv.COLOR_BGR2GRAY)

corners = cv.goodFeaturesToTrack(gray, 100, 0.01, 10)

corners = np.int0(corners)

for i in corners:
    x, y = i.ravel()
    cv.circle(img, (x, y), 3, 255, -1)

cv.imshow('image', img)

if cv.waitKey(0) & 0xff == 27:
    cv.destroyAllWindows()

In [ ]:
import cv2
import numpy as np

from pytesseract import image_to_string


def nothing(x):
    pass


cv2.namedWindow('image')

cv2.createTrackbar('th1','image',0,255,nothing)

cv2.createTrackbar('th2','image',255,255,nothing)

while True:
    img=cv2.imread('aadhar card.jpg')
    
    th1=cv2.getTrackbarPos('th1','image')
    
    th2=cv2.getTrackbarPos('th2','image')

    edge=cv2.Canny(img, th1, th2)
    
    cv2.imshow('image',img)
    cv2.imshow('edge',edge)

    text=image_to_string(edge)
    print (text)
    
    k=cv2.waitKey(1)
    if k==27:
        break

cv2.destroyAllWindows()

In [ ]:
pip install pytesseract

In [ ]:
from pytesseract import image_to_string

In [ ]:
import numpy as np
import cv2
from pytesseract import image_to_string

image=cv2.imread('aadhar card.jpg')

cv2.imshow('original image',image)

img=cv2.imread('aadhar card.jpg',0)

_,th1=cv2.threshold(img,110,255,cv2.THRESH_BINARY)

#th2=cv2.adaptiveThreshold(img,255,cv2.ADAPTIVE_THRESH_MEAN_C, cv2.THRESH_BINARY, 25, 5);

#th3=cv2.adaptiveThreshold(img,255,cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY, 25, 5);


cv2.imshow('image',img)

cv2.imshow('th1',th1)
#cv2.imshow('th2',th2)
#cv2.imshow('th3',th3)

text=image_to_string(th1)
print (text)
k=cv2.waitKey(0)
if k==27:
    cv2.destroyAllWindows()

# edge detection using canny,sobel,prewitt

In [ ]:
import cv2
import numpy as np

img = cv2.imread('messi5.jpg')
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
img_gaussian = cv2.GaussianBlur(gray,(3,3),0)

#canny
img_canny = cv2.Canny(img,100,200)

#sobel
img_sobelx = cv2.Sobel(img_gaussian,cv2.CV_8U,1,0,ksize=5)
img_sobely = cv2.Sobel(img_gaussian,cv2.CV_8U,0,1,ksize=5)
img_sobel = img_sobelx + img_sobely


#prewitt
kernelx = np.array([[1,1,1],[0,0,0],[-1,-1,-1]])
kernely = np.array([[-1,0,1],[-1,0,1],[-1,0,1]])
img_prewittx = cv2.filter2D(img_gaussian, -1, kernelx)
img_prewitty = cv2.filter2D(img_gaussian, -1, kernely)


cv2.imshow("Original Image", img)
cv2.imshow("Canny", img_canny)
cv2.imshow("Sobel X", img_sobelx)
cv2.imshow("Sobel Y", img_sobely)
cv2.imshow("Sobel", img_sobel)
cv2.imshow("Prewitt X", img_prewittx)
cv2.imshow("Prewitt Y", img_prewitty)
cv2.imshow("Prewitt", img_prewittx + img_prewitty)


cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
from PIL import image

In [ ]:
pip install pillow

In [ ]:
from PIL import Image
import os

for f in os.listdir('.'):
    if f.endswith('.jpg'):
        print (f)


img=Image.open('lena.jpg')
img.show()

In [ ]:
import numpy as np
import cv2
from pytesseract import image_to_string

image=cv2.imread('tfs2.png')

cv2.imshow('original image',image)

img=cv2.imread('tfs2.png',0)

_,th1=cv2.threshold(img,135,255,cv2.THRESH_BINARY)



th2=cv2.adaptiveThreshold(img,255,cv2.ADAPTIVE_THRESH_MEAN_C, cv2.THRESH_BINARY, 25, 5);

th3=cv2.adaptiveThreshold(img,255,cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY, 25, 5);

edge=cv2.Canny(img,135,255)

# cv2.imshow('image',img)

# cv2.imshow('th1',th1)
# cv2.imshow('th2',th2)
# cv2.imshow('th3',th3)
cv2.imshow('edge',edge)

text=image_to_string(image,lang='eng+hin')
print (text)
#f=open("pan2.txt","w+")
#f.write(text)
#f.close()
k=cv2.waitKey(0)
if k==27:
    cv2.destroyAllWindows()

In [ ]:
from pytesseract import image_to_string
from PIL import Image
img1 = Image.open('aadhar card.jpg')
txt = pytesseract.image_to_string(img1, lang='hin+eng')
print(txt)

# teseract-ocr for text extraction

In [ ]:
from PIL import Image
import PIL.Image

from pytesseract import image_to_string
import pytesseract

pytesseract.pytesseract.tesseract_cmd = "C:/Users/naveen.dagar/AppData/Local/Tesseract-OCR/tesseract.exe"
TESSDATA_PREFIX = "C:/Users/naveen.dagar/AppData/Local/Tesseract-OCR"
output = pytesseract.image_to_string(PIL.Image.open("C:/Users/naveen.dagar/start learning python/hin.jpg"), lang='eng+hin')
print (output)

# different techniques of edge detection on 20 nov 2019

In [ ]:
import cv2
import numpy as np


def nothing(x):
    pass


cv2.namedWindow('image')

cv2.createTrackbar('th1','image',0,255,nothing)

cv2.createTrackbar('th2','image',255,255,nothing)

while True:
    img=cv2.imread('sbi.png')
    
    th1=cv2.getTrackbarPos('th1','image')
    
    th2=cv2.getTrackbarPos('th2','image')
    
    edge=cv2.Canny(img,th1,th2) 

    
    cv2.imshow('image',img)
    cv2.imshow('edge',edge)
    
    k=cv2.waitKey(1)
    if k==27:
        break

cv2.destroyAllWindows()

In [ ]:
import numpy as np
import cv2
#from pytesseract import image_to_string

def nothing(x):
    pass


cv2.namedWindow('image')

cv2.createTrackbar('lt','image',0,255,nothing)

cv2.createTrackbar('ut','image',255,255,nothing)

while True:
    img=cv2.imread('aadhar card.jpg')
    
    lt=cv2.getTrackbarPos('lt','image')
    
    ut=cv2.getTrackbarPos('ut','image')

#image=cv2.imread('aadhar card.jpg')

#cv2.imshow('original image',image)

#img=cv2.imread('aadhar card.jpg',0)

    _,th1=cv2.threshold(img,lt,ut,cv2.THRESH_BINARY)
    #edge=cv2.Canny(img,lt,ut) 


#th2=cv2.adaptiveThreshold(img,255,cv2.ADAPTIVE_THRESH_MEAN_C, cv2.THRESH_BINARY, 25, 5);

#th3=cv2.adaptiveThreshold(img,255,cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY, 25, 5);


    cv2.imshow('image',img)

    cv2.imshow('th1',th1)
#cv2.imshow('th2',th2)
#cv2.imshow('th3',th3)

#text=image_to_string(img)
#print (text)
    k=cv2.waitKey(1)
    if k==27:
        break
cv2.destroyAllWindows()

In [ ]:
import os
os.getcwd()

In [ ]:
os.listdir()

In [ ]:
import cv2
import numpy as np


def nothing(x):
    pass


cv2.namedWindow('image')

cv2.createTrackbar('th1','image',0,255,nothing)

cv2.createTrackbar('th2','image',255,255,nothing)

while True:
    img=cv2.imread('pan1.jpg',0)
    
    th1=cv2.getTrackbarPos('th1','image')
    
    th2=cv2.getTrackbarPos('th2','image')
    
    _,thr=cv2.threshold(img,th1,th2,cv2.THRESH_BINARY)
    
    #edge=cv2.Canny(img,th1,th2) 

    
    cv2.imshow('image',img)
    #cv2.imshow('edge',edge)
    cv2.imshow('thr',thr)
    
    k=cv2.waitKey(1)
    if k==27:
        break

cv2.destroyAllWindows()

In [ ]:
from PIL import Image
im = Image.open('pan2.jfif')
im.save('pan0.jpg')  # or 'test.tif'

# storing the pancard extracted details into text file

In [ ]:
import numpy as np
import cv2
from pytesseract import image_to_string
import pytesseract


image=cv2.imread('tfs1.png')

#cv2.imshow('original image',image)

img=cv2.imread('tfs1.png',0)

_,th1=cv2.threshold(img,135,255,cv2.THRESH_BINARY)



th2=cv2.adaptiveThreshold(img,255,cv2.ADAPTIVE_THRESH_MEAN_C, cv2.THRESH_BINARY, 25, 5);

th3=cv2.adaptiveThreshold(img,255,cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY, 25, 5);

edge=cv2.Canny(img,135,255)

#cv2.imshow('image',img)

#cv2.imshow('th1',th1)
#cv2.imshow('th2',th2)
#cv2.imshow('th3',th3)
#cv2.imshow('edge',edge)

text=image_to_string(image,lang='eng+hin')
print (text)
file=open("tfs.txt","w+")
#for i in text:
with open("tfs.txt","w+", encoding = 'utf-8') as f:
    f.write(text)
file.close()
k=cv2.waitKey(1)
if k==27:
    cv2.destroyAllWindows()

In [ ]:
import numpy as np
import cv2
from pytesseract import image_to_string


image=cv2.imread('chq1.png')

cv2.imshow('original image',image)

img=cv2.imread('chq1.png',0)

_,th1=cv2.threshold(img,135,255,cv2.THRESH_BINARY)



th2=cv2.adaptiveThreshold(img,255,cv2.ADAPTIVE_THRESH_MEAN_C, cv2.THRESH_BINARY, 25, 5);

th3=cv2.adaptiveThreshold(img,255,cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY, 25, 5);

edge=cv2.Canny(img,135,255)

cv2.imshow('image',img)

cv2.imshow('th1',th1)
cv2.imshow('th2',th2)
cv2.imshow('th3',th3)
cv2.imshow('edge',edge)

text=image_to_string(image,lang='eng+hin')
print (text)
file=open("chq1.txt","w+")
with open("chq1.txt","w+", encoding = 'utf-8') as f:
    f.write(text)
file.close()
k=cv2.waitKey(1)
if k==27:
    cv2.destroyAllWindows()

In [ ]:
import numpy as np
import cv2
#from pytesseract import image_to_string

image=cv2.imread('chq6.jpg')

cv2.imshow('original image',image)

img=cv2.imread('chq6.jpg',0)

_,th1=cv2.threshold(img,135,255,cv2.THRESH_BINARY)



th2=cv2.adaptiveThreshold(img,255,cv2.ADAPTIVE_THRESH_MEAN_C, cv2.THRESH_BINARY, 25, 5);

th3=cv2.adaptiveThreshold(img,255,cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY, 25, 5);

edge=cv2.Canny(img,135,255)

cv2.imshow('image',img)

cv2.imshow('th1',th1)
cv2.imshow('th2',th2)
cv2.imshow('th3',th3)
cv2.imshow('edge',edge)

#text=image_to_string(image,lang='eng+hin')
print (text)
file=open("chq6.txt","w+")
with open("chq6.txt","w+", encoding = 'utf-8') as f:
    f.write(text)
#f=open("pan2.txt","w+")
#f.write(text)
#f.close()
k=cv2.waitKey(0)
if k==27:
    cv2.destroyAllWindows()

# Detect the cheque number

In [1]:
from skimage.segmentation import clear_border
from imutils import contours
import imutils
import numpy as np
import imutils
import cv2

def extract_digits_and_symbols(image, charCnts, minW=5, minH=15):
    
    charIter = charCnts.__iter__()
    rois = []
    locs = []

    
    while True:
        try:
            
            c = next(charIter)
            (cX, cY, cW, cH) = cv2.boundingRect(c)
            roi = None

            
            if cW >= minW and cH >= minH:
                # extract the ROI
                roi = image[cY:cY + cH, cX:cX + cW]
                rois.append(roi)
                locs.append((cX, cY, cX + cW, cY + cH))

            # otherwise, we are examining one of the special symbols
            else:
                
                parts = [c, next(charIter), next(charIter)]
                (sXA, sYA, sXB, sYB) = (np.inf, np.inf, -np.inf,
                    -np.inf)

                # loop over the parts
                for p in parts:
                    
                    (pX, pY, pW, pH) = cv2.boundingRect(p)
                    sXA = min(sXA, pX)
                    sYA = min(sYA, pY)
                    sXB = max(sXB, pX + pW)
                    sYB = max(sYB, pY + pH)

                # extract the ROI
                roi = image[sYA:sYB, sXA:sXB]
                rois.append(roi)
                locs.append((sXA, sYA, sXB, sYB))

        
        except StopIteration:
            break

    # return a tuple of the ROIs and locations
    return (rois, locs)

charNames = ["1", "2", "3", "4", "5", "6", "7", "8", "9", "0",
    "T", "U", "A", "D"]


ref = cv2.imread("C:/Users/naveen.dagar/start_learning_python/bank-check-ocr-part-ii/bank-check-ocr-2/micr_e13b_reference.png")
ref = cv2.cvtColor(ref, cv2.COLOR_BGR2GRAY)
ref = imutils.resize(ref, width=400)
ref = cv2.threshold(ref, 0, 255, cv2.THRESH_BINARY_INV |
    cv2.THRESH_OTSU)[1]

refCnts = cv2.findContours(ref.copy(), cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE)
refCnts = imutils.grab_contours(refCnts)
refCnts = contours.sort_contours(refCnts, method="left-to-right")[0]

refROIs = extract_digits_and_symbols(ref, refCnts,
    minW=10, minH=20)[0]
chars = {}

# loop over the reference ROIs
for (name, roi) in zip(charNames, refROIs):
    
    roi = cv2.resize(roi, (36, 36)) 
    chars[name] = roi

rectKernel = cv2.getStructuringElement(cv2.MORPH_RECT, (17, 7))
output = []


image = cv2.imread("C:/Users/naveen.dagar/start_learning_python/bank-check-ocr-part-ii/bank-check-ocr-2/ch5.png")
(h, w,) = image.shape[:2]
delta = int(h - (h * 0.2))
bottom = image[delta:h, 0:w]


gray = cv2.cvtColor(bottom, cv2.COLOR_BGR2GRAY)
blackhat = cv2.morphologyEx(gray, cv2.MORPH_BLACKHAT, rectKernel)


gradX = cv2.Sobel(blackhat, ddepth=cv2.CV_32F, dx=1, dy=0,ksize=-1)
gradX = np.absolute(gradX)
(minVal, maxVal) = (np.min(gradX), np.max(gradX))
gradX = (255 * ((gradX - minVal) / (maxVal - minVal)))
gradX = gradX.astype("uint8")


gradX = cv2.morphologyEx(gradX, cv2.MORPH_CLOSE, rectKernel)
thresh = cv2.threshold(gradX, 0, 255,cv2.THRESH_BINARY | cv2.THRESH_OTSU)[1]

thresh = clear_border(thresh)


groupCnts = cv2.findContours(thresh.copy(), cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE)
groupCnts = groupCnts[0]
groupLocs = []

# loop over the group contours
for (i, c) in enumerate(groupCnts):
    # compute the bounding box of the contour
    (x, y, w, h) = cv2.boundingRect(c)

    
    if w > 20 and h > 15:
        groupLocs.append((x, y, w, h))


groupLocs = sorted(groupLocs, key=lambda x:x[0])


for (gX, gY, gW, gH) in groupLocs:
    
    groupOutput = []

    
    group = gray[gY - 5:gY + gH + 5, gX - 5:gX + gW + 5]
    group = cv2.threshold(group, 0, 255,cv2.THRESH_BINARY_INV | cv2.THRESH_OTSU)[1]

    cv2.imshow("Group", group)
    cv2.waitKey(0)

    
    charCnts = cv2.findContours(group.copy(), cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE)
    charCnts = imutils.grab_contours(charCnts)
    charCnts = contours.sort_contours(charCnts,method="left-to-right")[0]

    
    (rois, locs) = extract_digits_and_symbols(group, charCnts)

    
    for roi in rois:
        
        scores = []
        roi = cv2.resize(roi, (36, 36))

        
        for charName in charNames:
            
            result = cv2.matchTemplate(roi, chars[charName],
                cv2.TM_CCOEFF)
            (_, score, _, _) = cv2.minMaxLoc(result)
            scores.append(score)

      
        groupOutput.append(charNames[np.argmax(scores)])

    
    cv2.rectangle(image, (gX - 10, gY + delta - 10),(gX + gW + 10, gY + gY + delta), (0, 0, 255), 2)
    cv2.putText(image, "".join(groupOutput),(gX - 10, gY + delta - 25), cv2.FONT_HERSHEY_SIMPLEX,0.95, (0, 0, 255), 3)

    
    output.append("".join(groupOutput))


print("Check OCR: {}".format(" ".join(output)))
cv2.imshow("Check OCR", image)

cv2.waitKey(0)
cv2.destroyAllWindows()

Check OCR: T011300142T 12345678U 0101


In [ ]:
import cv2
img=cv2.imread('chq1.png')
cv2.imshow('chq1',img)

In [ ]:
import cv2
img=cv2.imread('chq1.png',0)
cv2.imshow('image',img)
print(img)
k=cv2.waitKey(0)
if k==27:
    cv2.destroyAllWindows()

In [ ]:
import pandas

In [ ]:
import sklearn

In [ ]:
pip install sklearn

In [ ]:
pip install Quand

# Machine learning using python

In [ ]:
import pandas as pd
import quandl
import math
import numpy as np
from sklearn import preprocessing,cross_decomposition,svm
from sklearn.linear_model import LinearRegression

df=quandl.get('WIKI/GOOGL')
#print(df.head())
df=df[['Adj. Open','Adj. High','Adj. Low','Adj. Close','Adj. Volume']]
df['HL_PCT']=(df['Adj. High']-df['Adj. Close'])/df['Adj. Close']*100.0
df['PCT_change']=(df['Adj. Close']-df['Adj. Open'])/df['Adj. Open']*100.0

df=df[['Adj. Close','HL_PCT','PCT_change','Adj. Volume']]



forecast_col='Adj. Close'
df.fillna(-99999,inplace=True)

forecast_out=int(math.ceil(0.01*len(df)))

df['label']=df[forecast_col].shift(-forecast_out)
df.dropna(inplace=True)




X=np.array(df.drop(['label'],1))

y=np.array(df['label'])

X=preprocessing.scale(X)

df.dropna(inplace=True)
y=np.array(df['label'])
print(len(X),len(y))


In [ ]:
from sklearn.datasets import load_iris

iris=load_iris()
type(iris)

In [ ]:
print (iris.data)

In [ ]:
print(iris.feature_names)

In [ ]:
print(iris.target)

In [ ]:
print(iris.target_names)

In [ ]:
print(type(iris.data))
print(type(iris.target))

In [ ]:
print(iris.data.shape)

In [ ]:
print(iris.target.shape)

# detection of the signature

In [ ]:
import cv2
import matplotlib.pyplot as plt
from skimage import measure, morphology
from skimage.color import label2rgb
from skimage.measure import regionprops

# read the input image
img = cv2.imread('chq2.jpg', 0)
img = cv2.threshold(img, 128, 255, cv2.THRESH_BINARY)[1]  # ensure binary
#img=cv2.adaptiveThreshold(img,255,cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY, 25, 5);
#img=cv2.Canny(img,125,255)
# connected component analysis by scikit-learn framework
blobs = img > img.mean()
blobs_labels = measure.label(blobs, background=1)
image_label_overlay = label2rgb(blobs_labels, image=img)

fig, ax = plt.subplots(figsize=(10, 6))


the_biggest_component = 0
total_area = 0
counter = 0
average = 0.0
for region in regionprops(blobs_labels):
    if (region.area > 10):
        total_area = total_area + region.area
        counter = counter + 1
    # print region.area # (for debugging)
    # take regions with large enough areas
    if (region.area >= 250):
        if (region.area > the_biggest_component):
            the_biggest_component = region.area

average = (total_area/counter)
#print("the_biggest_component: " + str(the_biggest_component))
#print("average: " + str(average))

# experimental-based ratio calculation, modify it for your cases
# a4_constant is used as a threshold value to remove connected pixels
# are smaller than a4_constant for A4 size scanned documents
a4_constant = ((average/84.0)*250.0)+100
#print("a4_constant: " + str(a4_constant))

# remove the connected pixels are smaller than a4_constant
b = morphology.remove_small_objects(blobs_labels, a4_constant)
# save the the pre-version which is the image is labelled with colors
# as considering connected components
plt.imsave('pre_chq.png', b)

# read the pre-version
img = cv2.imread('pre_chq.png', 0)
# ensure binary
img = cv2.threshold(img, 0, 255, cv2.THRESH_BINARY_INV | cv2.THRESH_OTSU)[1]
# save the the result
#cv2.imwrite("./outputs/output.png", img)
cv2.imshow('img',img)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [ ]:
import numpy as np
import cv2


img = cv2.imread('sign.jpg', 0)
img = cv2.threshold(img, 128, 255, cv2.THRESH_BINARY)[1]
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()


# Comparing two signature using SSIM and MSE

In [ ]:
#from skimage.measure import structural_similarity as ssim
import matplotlib.pyplot as plt
import numpy as np
import cv2
from skimage import measure


def mse(imageA, imageB):
    # the 'Mean Squared Error' between the two images is the
    # sum of the squared difference between the two images;
    # NOTE: the two images must have the same dimension
    err = np.sum((imageA.astype("float") - imageB.astype("float")) ** 2)
    err /= float(imageA.shape[0] * imageA.shape[1])
    
    # return the MSE, the lower the error, the more "similar"
    # the two images are
    return err

def compare_images(imageA, imageB, title):
    # compute the mean squared error and structural similarity
    # index for the images
    m = mse(imageA, imageB)
    #s = ssim(imageA, imageB)
    s = measure.compare_ssim(imageA, imageB)

    # setup the figure
    fig = plt.figure(title)
    plt.suptitle("MSE: %.2f, SSIM: %.2f" % (m, s))

    # show first image
    ax = fig.add_subplot(1, 2, 1)
    plt.imshow(imageA, cmap = plt.cm.gray)
    plt.axis("off")

    # show the second image
    ax = fig.add_subplot(1, 2, 2)
    plt.imshow(imageB, cmap = plt.cm.gray)
    plt.axis("off")

    # show the images
    plt.show()

# load the images -- the original, the original + contrast,
# and the original + photoshop
original = cv2.imread("C:/Users/naveen.dagar/start learning python/sign.jpg")
contrast = cv2.imread("C:/Users/naveen.dagar/start learning python/sr1.jpg")
#shopped = cv2.imread("C:/Users/naveen.dagar/start learning python/python-compare-two-images/python-compare-two-images/images/jp_gates_contrast.png")

# convert the images to grayscale
original = cv2.cvtColor(original, cv2.COLOR_BGR2GRAY)
contrast = cv2.cvtColor(contrast, cv2.COLOR_BGR2GRAY)
#shopped = cv2.cvtColor(shopped, cv2.COLOR_BGR2GRAY)

# initialize the figure
fig = plt.figure("Images")
images = ("Original", original), ("Contrast", contrast)

# loop over the images
for (i, (name, image)) in enumerate(images):
# show the image
    ax = fig.add_subplot(1, 3, i + 1)
    ax.set_title(name)
    plt.imshow(image, cmap = plt.cm.gray)
    plt.axis("off")

# show the figure
plt.show()

# compare the images
compare_images(original, original, "Original vs. Original")
compare_images(original, contrast, "Original vs. Contrast")
#compare_images(original, shopped, "Original vs. Photoshopped")

# work on 29 nov.

In [ ]:
import cv2
import matplotlib.pyplot as plt
from skimage import measure, morphology
from skimage.color import label2rgb
from skimage.measure import regionprops

# read the input image
img = cv2.imread('chq2.jpg', 0)
img = cv2.threshold(img, 128, 255, cv2.THRESH_BINARY)[1]  # ensure binary
#img=cv2.adaptiveThreshold(img,255,cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY, 25, 5);
#img=cv2.Canny(img,125,255)
# connected component analysis by scikit-learn framework
blobs = img > img.mean()
blobs_labels = measure.label(blobs, background=1)
image_label_overlay = label2rgb(blobs_labels, image=img)

fig, ax = plt.subplots(figsize=(10, 6))


the_biggest_component = 0
total_area = 0
counter = 0
average = 0.0
for region in regionprops(blobs_labels):
    if (region.area > 10):
        total_area = total_area + region.area
        counter = counter + 1
    # print region.area # (for debugging)
    # take regions with large enough areas
    if (region.area >= 250):
        if (region.area > the_biggest_component):
            the_biggest_component = region.area

average = (total_area/counter)
#print("the_biggest_component: " + str(the_biggest_component))
#print("average: " + str(average))

# experimental-based ratio calculation, modify it for your cases
# a4_constant is used as a threshold value to remove connected pixels
# are smaller than a4_constant for A4 size scanned documents
a4_constant = ((average/95.0)*250.0)+100
#print("a4_constant: " + str(a4_constant))

# remove the connected pixels are smaller than a4_constant
b = morphology.remove_small_objects(blobs_labels, a4_constant)
# save the the pre-version which is the image is labelled with colors
# as considering connected components
plt.imsave('pre_chq.png', b)

# read the pre-version
img = cv2.imread('pre_chq.png', 0)
# ensure binary
#img=cv2.adaptiveThreshold(img,255,cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY, 25, 5);
img = cv2.threshold(img, 0, 255, cv2.THRESH_BINARY_INV | cv2.THRESH_OTSU)[1]
# save the the result
#cv2.imwrite("./outputs/output.png", img)
cv2.imshow('img',img)
cv2.waitKey()
cv2.destroyAllWindows()

In [ ]:
import argparse
import os
import sys

import cv2
import editdistance
import numpy as np
import tensorflow as tf

from DataLoader import Batch, DataLoader, FilePaths
from SamplePreprocessor import preprocessor, wer
from Model import DecoderType, Model
from SpellChecker import correct_sentence


def train(model, loader):
    """ Train the neural network """
    epoch = 0  # Number of training epochs since start
    bestCharErrorRate = float('inf')  # Best valdiation character error rate
    noImprovementSince = 0  # Number of epochs no improvement of character error rate occured
    earlyStopping = 25  # Stop training after this number of epochs without improvement
    batchNum = 0

    totalEpoch = loader.trainSamples//Model.batchSize # loader.numTrainSamplesPerEpoch

    while True:
        epoch += 1
        print('Epoch:', epoch, '/', totalEpoch)

        # Train
        print('Train neural network')
        loader.trainSet()
        while loader.hasNext():
            batchNum += 1
            iterInfo = loader.getIteratorInfo()
            batch = loader.getNext()
            loss = model.trainBatch(batch, batchNum)
            print('Batch:', iterInfo[0], '/', iterInfo[1], 'Loss:', loss)

        # Validate
        charErrorRate, addressAccuracy, wordErrorRate = validate(model, loader)
        cer_summary = tf.Summary(value=[tf.Summary.Value(
            tag='charErrorRate', simple_value=charErrorRate)])  # Tensorboard: Track charErrorRate
        # Tensorboard: Add cer_summary to writer
        model.writer.add_summary(cer_summary, epoch)
        address_summary = tf.Summary(value=[tf.Summary.Value(
            tag='addressAccuracy', simple_value=addressAccuracy)])  # Tensorboard: Track addressAccuracy
        # Tensorboard: Add address_summary to writer
        model.writer.add_summary(address_summary, epoch)
        wer_summary = tf.Summary(value=[tf.Summary.Value(
            tag='wordErrorRate', simple_value=wordErrorRate)])  # Tensorboard: Track wordErrorRate
        # Tensorboard: Add wer_summary to writer
        model.writer.add_summary(wer_summary, epoch)

        # If best validation accuracy so far, save model parameters
        if charErrorRate < bestCharErrorRate:
            print('Character error rate improved, save model')
            bestCharErrorRate = charErrorRate
            noImprovementSince = 0
            model.save()
            open(FilePaths.fnAccuracy, 'w').write(
                'Validation character error rate of saved model: %f%%' % (charErrorRate*100.0))
        else:
            print('Character error rate not improved')
            noImprovementSince += 1

        # Stop training if no more improvement in the last x epochs
        if noImprovementSince >= earlyStopping:
            print('No more improvement since %d epochs. Training stopped.' %
                  earlyStopping)
            break


def validate(model, loader):
    """ Validate neural network """
    print('Validate neural network')
    loader.validationSet()
    numCharErr = 0
    numCharTotal = 0
    numWordOK = 0
    numWordTotal = 0

    totalCER = []
    totalWER = []
    while loader.hasNext():
        iterInfo = loader.getIteratorInfo()
        print('Batch:', iterInfo[0], '/', iterInfo[1])
        batch = loader.getNext()
        recognized = model.inferBatch(batch)

        print('Ground truth -> Recognized')
        for i in range(len(recognized)):
            numWordOK += 1 if batch.gtTexts[i] == recognized[i] else 0
            numWordTotal += 1
            dist = editdistance.eval(recognized[i], batch.gtTexts[i])
            ## editdistance
            currCER = dist/max(len(recognized[i]), len(batch.gtTexts[i]))
            totalCER.append(currCER)

            currWER = wer(recognized[i].split(), batch.gtTexts[i].split())
            totalWER.append(currWER)

            numCharErr += dist
            numCharTotal += len(batch.gtTexts[i])
            print('[OK]' if dist == 0 else '[ERR:%d]' % dist, '"' +
                  batch.gtTexts[i] + '"', '->', '"' + recognized[i] + '"')

    # Print validation result
    charErrorRate = sum(totalCER)/len(totalCER)
    addressAccuracy = numWordOK / numWordTotal
    wordErrorRate = sum(totalWER)/len(totalWER)
    print('Character error rate: %f%%. Address accuracy: %f%%. Word error rate: %f%%' %
          (charErrorRate*100.0, addressAccuracy*100.0, wordErrorRate*100.0))
    return charErrorRate, addressAccuracy, wordErrorRate


def load_different_image():
    imgs = []
    for i in range(1, Model.batchSize):
       imgs.append(preprocessor(cv2.imread("../data/check_image/a ({}).png".format(i), cv2.IMREAD_GRAYSCALE), Model.imgSize, enhance=False))
    return imgs


def generate_random_images():
    return np.random.random((Model.batchSize, Model.imgSize[0], Model.imgSize[1]))


def infer(model, fnImg):
    """ Recognize text in image provided by file path """
    img = preprocessor(cv2.imread(fnImg, cv2.IMREAD_GRAYSCALE), imgSize=Model.imgSize)
    if img is None:
        print("Image not found")

    imgs = load_different_image()
    imgs = [img] + imgs
    batch = Batch(None, imgs)
    recognized = model.inferBatch(batch)  # recognize text

    print("Without Correction", recognized[0])
    print("With Correction", correct_sentence(recognized[0]))
    return recognized[0]


def main():
    """ Main function """
    # Opptional command line args
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--train", help="train the neural network", action="store_true")
    parser.add_argument(
        "--validate", help="validate the neural network", action="store_true")
    parser.add_argument(
        "--wordbeamsearch", help="use word beam search instead of best path decoding", action="store_true")
    args = parser.parse_args()

    decoderType = DecoderType.BestPath
    if args.wordbeamsearch:
        decoderType = DecoderType.WordBeamSearch

    # Train or validate on Cinnamon dataset
    if args.train or args.validate:
        # Load training data, create TF model
        loader = DataLoader(FilePaths.fnTrain, Model.batchSize,
                            Model.imgSize, Model.maxTextLen, load_aug=True)

        # Execute training or validation
        if args.train:
            model = Model(loader.charList, decoderType)
            train(model, loader)
        elif args.validate:
            model = Model(loader.charList, decoderType, mustRestore=False)
            validate(model, loader)

    # Infer text on test image
    else:
        print(open(FilePaths.fnAccuracy).read())
        model = Model(open(FilePaths.fnCharList).read(),
                      decoderType, mustRestore=False)
        infer(model, FilePaths.fnInfer)


def infer_by_web(path, option):
    decoderType = DecoderType.BestPath
    print(open(FilePaths.fnAccuracy).read())
    model = Model(open(FilePaths.fnCharList).read(),
                  decoderType, mustRestore=False)
    recognized = infer(model, path)

    return recognized


if __name__ == '__main__':
    main()